main:
  steps: all
dataset:
  url: https://www.sidc.be/silso/DATA/SN_m_tot_V2.0.txt
  path: data
  dataset_file_name: ""
  train_set_file_name: train.csv
  test_set_file_name: test.csv
model:
  window_size: 30
  batch_size: 32
  training_epochs: 10
  shuffle_buffer_size: 1000
